spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8080}

googleai:
  api:
    key: ${GOOGLE_AI_KEY}

gemini:
  baseurl: "https://generativelanguage.googleapis.com"
  model: "gemini-2.5-flash"